#! /usr/bin/env python3

from mesh_rviz.mesh_publisher import MeshPublisher
import rospy

if __name__ == "__main__":
    
    try:
        MeshPublisher.run(name='test')
    except rospy.ROSInterruptException:
        pass
